export const salesData = {
  filters: {
    dateFrom: "25.04.2026",
    dateTo: "26.04.2026",
    employee: "Все сотрудники",
    status: "Все статусы",
  },
  title: "Продажи за период 25.04 — 26.04.2026",
  resultLabel: "Показано 1-8 из 10 продаж",
  sales: [
    {
      id: "test-sale-1",
      date: "10.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-brand-500",
      client: "Тест",
      trip: "Тест 7н",
      quantity: 2,
      basePrice: "₽1",
      discount: "-₽1",
      total: "₽1",
    },
    {
      id: "test-sale-2",
      date: "09.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-violet-500",
      client: "Тест",
      trip: "Тест 10н",
      quantity: 1,
      basePrice: "₽1",
      discount: "-₽1",
      total: "₽1",
    },
    {
      id: "test-sale-3",
      date: "08.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-emerald-500",
      client: "Тест",
      trip: "Тест 5н",
      quantity: 2,
      basePrice: "₽2",
      discount: "-₽0",
      total: "₽2",
    },
    {
      id: "test-sale-4",
      date: "07.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-amber-500",
      client: "Тест",
      trip: "Тест 14н",
      quantity: 1,
      basePrice: "₽3",
      discount: "-₽1",
      total: "₽2",
    },
    {
      id: "test-sale-5",
      date: "07.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-rose-500",
      client: "Тест",
      trip: "Тест 8н",
      quantity: 2,
      basePrice: "₽4",
      discount: "-₽0",
      total: "₽4",
    },
    {
      id: "test-sale-6",
      date: "06.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-brand-600",
      client: "Тест",
      trip: "Тест 9н",
      quantity: 1,
      basePrice: "₽5",
      discount: "-₽1",
      total: "₽4",
    },
    {
      id: "test-sale-7",
      date: "05.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-purple-500",
      client: "Тест",
      trip: "Тест 7н",
      quantity: 2,
      basePrice: "₽6",
      discount: "-₽0",
      total: "₽6",
    },
    {
      id: "test-sale-8",
      date: "04.04.2026",
      employee: "Тест",
      initials: "Т",
      avatarTone: "bg-teal-500",
      client: "Тест",
      trip: "Тест 6н",
      quantity: 1,
      basePrice: "₽7",
      discount: "-₽1",
      total: "₽6",
    },
  ],
  summary: {
    quantity: 12,
    basePrice: "₽1",
    discount: "-₽1",
    total: "₽1",
  },
};
