import {
  ClientsIcon,
  LossIcon,
  RevenueIcon,
  SoldIcon,
} from "../../shared/ui/Icons";

export const dashboardData = {
  urgentTrips: ["Турция (12 апр.)", "Египет (13 апр.)", "Кипр (14 апр.)"],
  stats: [
    {
      id: "sales",
      label: "Путёвок продано",
      value: "0",
      trend: "+0% за месяц",
      tone: "border-t-brand-500",
      icon: SoldIcon,
    },
    {
      id: "clients",
      label: "Клиентов",
      value: "0",
      trend: "0 новых",
      tone: "border-t-emerald-500",
      icon: ClientsIcon,
    },
    {
      id: "revenue",
      label: "Выручка",
      value: "0 ₽",
      trend: "+0%",
      tone: "border-t-violet-500",
      icon: RevenueIcon,
    },
    {
      id: "discount-loss",
      label: "Потери на скидках",
      value: "₽0",
      trend: "-₽0",
      tone: "border-t-rose-500",
      icon: LossIcon,
    },
  ],
  recentSales: [
    {
      employee: "Тест",
      initials: "Т",
      destination: "Тест",
      date: "10.04.2026",
      status: "Отменена",
      color: "bg-brand-500",
    },
    {
      employee: "Тест",
      initials: "Т",
      destination: "Тест",
      date: "09.04.2026",
      status: "Отменена",
      color: "bg-violet-500",
    },
    {
      employee: "Тест",
      initials: "Т",
      destination: "Тест",
      date: "08.04.2026",
      status: "Оформлена",
      color: "bg-emerald-500",
    },
    {
      employee: "Тест",
      initials: "Т",
      destination: "Тест",
      date: "07.04.2026",
      status: "Отправлен",
      color: "bg-amber-500",
    },
    {
      employee: "Тест",
      initials: "Т",
      destination: "Тест",
      date: "07.04.2026",
      status: "Отменена",
      color: "bg-rose-500",
    },
    {
      employee: "Тест",
      initials: "Т",
      destination: "Тест",
      date: "06.04.2026",
      status: "Оформлена",
      color: "bg-brand-500",
    },
  ],
  popularTrips: [
    {
      title: "Тест",
      location: "Анталья",
      nights: 7,
      price: "₽1",
      sold: 0,
      total: 0,
      current: 0,
      color: "bg-brand-500",
    },
    {
      title: "Тест",
      location: "Тест",
      nights: 1,
      price: "₽2",
      sold: 10,
      total: 30,
      current: 22,
      color: "bg-emerald-500",
    },
    {
      title: "Тест",
      location: "Тест",
      nights: 2,
      price: "₽3",
      sold: 20,
      total: 20,
      current: 12,
      color: "bg-violet-500",
    },
    {
      title: "Тест",
      location: "Тест",
      nights: 5,
      price: "₽4",
      sold: 100,
      total: 20,
      current: 9,
      color: "bg-amber-500",
    },
  ],
};
