export const travelData = {
  filters: {
    city: "Все города",
    dateFrom: "10.04.2026",
    dateTo: "30.06.2026",
    priceFrom: "0",
    priceTo: "300 000",
    urgentOnly: false,
  },
  resultRange: "Показано 1-9 из 10 результатов",
  pagination: [1, 2],
  tours: [
    {
      id: "test-tour-1",
      title: "Тест",
      city: "test",
      startDate: "12.04.2026",
      endDate: "19.04.2026",
      price: "₽1",
      seatsLabel: "4 места",
      seatsTone: "danger",
      services: ["AI", "Перелёт", "Трансфер"],
      status: "Горящая",
      statusTone: "hot",
      highlighted: true,
    },
    {
      id: "test-tour-2",
      title: "Тест",
      city: "test",
      startDate: "13.04.2026",
      endDate: "23.04.2026",
      price: "₽1",
      seatsLabel: "2 места",
      seatsTone: "danger",
      services: ["BB", "Перелёт"],
      status: "Успех",
      statusTone: "success",
      highlighted: false,
    },
  ],
};
