export const clientsData = {
  searchPlaceholder: "Поиск по имени, телефону, паспорту...",
  totalClientsLabel: "87 клиентов",
  summary: [
    {
      id: "total",
      label: "Всего клиентов",
      value: "0",
      icon: "users",
      iconTone: "bg-brand-50 text-brand-500",
    },
    {
      id: "discount",
      label: "Со скидкой",
      value: "0",
      icon: "star",
      iconTone: "bg-emerald-50 text-emerald-500",
    },
    {
      id: "active-trip",
      label: "Сейчас в туре",
      value: "0",
      icon: "plane",
      iconTone: "bg-violet-50 text-violet-500",
    },
    {
      id: "new",
      label: "Новых за месяц",
      value: "0",
      icon: "spark",
      iconTone: "bg-amber-50 text-amber-500",
    },
  ],
  tabs: [
    { id: "all", label: "Все", active: true },
    { id: "discount", label: "Со скидкой", active: false },
    { id: "trip", label: "В туре", active: false },
    { id: "vip", label: "VIP", active: false },
  ],
  clients: [
    {
      id: "1",
      fullName: "Тест Тест Тест",
      email: "a.smirnov@mail.ru",
      initials: "Т",
      avatarTone: "bg-brand-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "-10%",
      discountTone: "success",
      currentTrip: "Страна 7н / 12.04",
      purchases: 1,
      highlighted: true,
    },
    {
      id: "2",
      fullName: "Тест Тест Тест",
      email: "test@gmail.com",
      initials: "Т",
      avatarTone: "bg-emerald-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "-15%",
      discountTone: "success",
      currentTrip: "Страна 7н / 25.04",
      purchases: 1,
      highlighted: true,
    },
    {
      id: "3",
      fullName: "Тест Тест Тест",
      email: "test@yandex.ru",
      initials: "Т",
      avatarTone: "bg-violet-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "—",
      discountTone: "neutral",
      currentTrip: "—",
      purchases: 1,
      highlighted: false,
    },
    {
      id: "4",
      fullName: "Тест Тест Тест",
      email: "test@mail.ru",
      initials: "Т",
      avatarTone: "bg-amber-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "-7%",
      discountTone: "success",
      currentTrip: "Страна 5н / 01.05",
      purchases: 1,
      highlighted: true,
    },
    {
      id: "5",
      fullName: "Тест Тест Тест",
      email: "test@gmail.com",
      initials: "Т",
      avatarTone: "bg-rose-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "—",
      discountTone: "neutral",
      currentTrip: "—",
      purchases: 1,
      highlighted: false,
    },
    {
      id: "6",
      fullName: "Тест Тест Тест",
      email: "test@bk.ru",
      initials: "Т",
      avatarTone: "bg-sky-600",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "-20%",
      discountTone: "success",
      currentTrip: "Страна 14н / 10.05",
      purchases: 1,
      highlighted: true,
    },
    {
      id: "7",
      fullName: "Тест Тест Тест",
      email: "test@yandex.ru",
      initials: "Т",
      avatarTone: "bg-teal-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "—",
      discountTone: "neutral",
      currentTrip: "—",
      purchases: 1,
      highlighted: false,
    },
    {
      id: "8",
      fullName: "Тест Тест Тест",
      email: "testa@mail.ru",
      initials: "Т",
      avatarTone: "bg-purple-500",
      phone: "+7 (900) 000-00-00",
      passportMasked: "**** 111111",
      discount: "-5%",
      discountTone: "success",
      currentTrip: "Страна 8н / 15.05",
      purchases: 1,
      highlighted: true,
    },
  ],
  resultLabel: "Показано 1-8 из 10 клиентов",
  pagination: {
    pages: [1, 2, 3, "…", 11],
    currentPage: 1,
  },
};
