import {
  AverageBillIcon,
  RevenueSummaryIcon,
  SalesLossIcon,
  SalesReportIcon,
} from "../../shared/ui/Icons";

export const reportsData = {
  filters: {
    dateFrom: "01.04.2026",
    dateTo: "10.04.2026",
    employee: "Все сотрудники",
    destination: "Все направления",
    reportType: "Общий отчёт",
  },
  summary: [
    {
      id: "sales",
      label: "Продаж",
      value: "48",
      trend: "+12 за период",
      tone: "border-t-brand-500",
      icon: SalesReportIcon,
    },
    {
      id: "revenue",
      label: "Выручка",
      value: "₽3 845 000",
      trend: "+₽420 000",
      tone: "border-t-emerald-500",
      icon: RevenueSummaryIcon,
    },
    {
      id: "average",
      label: "Средний чек",
      value: "₽80 100",
      trend: "+6.4%",
      tone: "border-t-violet-500",
      icon: AverageBillIcon,
    },
    {
      id: "discounts",
      label: "Скидки",
      value: "₽186 500",
      trend: "-₽24 000",
      tone: "border-t-rose-500",
      icon: SalesLossIcon,
    },
  ],
  employeeReportTitle: "Сводка по сотрудникам",
  employeeReport: [
    {
      id: "employee-1",
      employee: "Анна Тестова",
      initials: "АТ",
      avatarTone: "bg-brand-500",
      sales: 14,
      revenue: "₽1 248 000",
      average: "₽89 100",
      discount: "₽52 000",
    },
    {
      id: "employee-2",
      employee: "Иван Тестов",
      initials: "ИТ",
      avatarTone: "bg-emerald-500",
      sales: 12,
      revenue: "₽978 000",
      average: "₽81 500",
      discount: "₽41 500",
    },
    {
      id: "employee-3",
      employee: "Мария Тестова",
      initials: "МТ",
      avatarTone: "bg-violet-500",
      sales: 11,
      revenue: "₽854 000",
      average: "₽77 600",
      discount: "₽35 000",
    },
    {
      id: "employee-4",
      employee: "Дмитрий Тестов",
      initials: "ДТ",
      avatarTone: "bg-amber-500",
      sales: 11,
      revenue: "₽765 000",
      average: "₽69 500",
      discount: "₽58 000",
    },
  ],
  destinationReportTitle: "Сводка по направлениям",
  destinationReport: [
    {
      id: "destination-1",
      destination: "Турция",
      sold: 16,
      clients: 29,
      revenue: "₽1 420 000",
      share: "37%",
      progress: 37,
      progressTone: "bg-brand-500",
    },
    {
      id: "destination-2",
      destination: "Египет",
      sold: 12,
      clients: 20,
      revenue: "₽910 000",
      share: "24%",
      progress: 24,
      progressTone: "bg-emerald-500",
    },
    {
      id: "destination-3",
      destination: "ОАЭ",
      sold: 10,
      clients: 15,
      revenue: "₽835 000",
      share: "22%",
      progress: 22,
      progressTone: "bg-violet-500",
    },
    {
      id: "destination-4",
      destination: "Таиланд",
      sold: 10,
      clients: 14,
      revenue: "₽680 000",
      share: "17%",
      progress: 17,
      progressTone: "bg-amber-500",
    },
  ],
  topEmployeesTitle: "Топ сотрудники",
  topEmployees: [
    {
      id: "top-1",
      name: "Анна Тестова",
      value: "₽1 248 000",
      progress: 100,
      color: "bg-brand-500",
    },
    {
      id: "top-2",
      name: "Иван Тестов",
      value: "₽978 000",
      progress: 78,
      color: "bg-emerald-500",
    },
    {
      id: "top-3",
      name: "Мария Тестова",
      value: "₽854 000",
      progress: 68,
      color: "bg-violet-500",
    },
  ],
  topTripsTitle: "Топ направления",
  topTrips: [
    {
      id: "trip-1",
      name: "Турция",
      value: "16 продаж",
      progress: 100,
      color: "bg-brand-500",
    },
    {
      id: "trip-2",
      name: "Египет",
      value: "12 продаж",
      progress: 75,
      color: "bg-emerald-500",
    },
    {
      id: "trip-3",
      name: "ОАЭ",
      value: "10 продаж",
      progress: 63,
      color: "bg-violet-500",
    },
  ],
};
